trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - script: |
      cd frontend
      npm install
      npm run build
      cd ../backend
      npm install
    displayName: 'Build Frontend and Backend'

- job: Deploy
  steps:
  - script: |
      echo "Deploying application..."
    displayName: 'Deploy Application'